POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"atomek",
    "password":"password3"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"atomek",
    "password":"password3"
}
###
POST http://localhost:3000/simpleCalc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b21layIsImlhdCI6MTc0ODc0MDgzMCwiZXhwIjoxNzQ4NzQyNjMwfQ.xJLQzJE4lZJU4E46bvONsElLiIH3NR7jm9hoA6dT8KA

{
    "usagePerMonth": 170.3,
    "pricePerKWH": 2444.5,
    "fotoSize": 55.1
}
###
GET http://localhost:3000/simpleCalc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b21layIsImlhdCI6MTc0ODc0MDgzMCwiZXhwIjoxNzQ4NzQyNjMwfQ.xJLQzJE4lZJU4E46bvONsElLiIH3NR7jm9hoA6dT8KA

###
GET  http://localhost:3000/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b21layIsImlhdCI6MTc0ODc0MTAwOCwiZXhwIjoxNzQ4ODI3NDA4fQ.x8c0UqHwWkbVSElIVvou-dNmDzANQYgqvZEVWyBqxiA

###
POST http://localhost:3000/logout 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b21layIsImlhdCI6MTc0ODc0MTAwOCwiZXhwIjoxNzQ4ODI3NDA4fQ.x8c0UqHwWkbVSElIVvou-dNmDzANQYgqvZEVWyBqxiA

###
GET http://localhost:3000/deviceCategories 

###
POST http://localhost:3000/advancedCalc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b21layIsImlhdCI6MTc0ODc0MTMwNCwiZXhwIjoxNzQ4NzQzMTA0fQ.FMNu-1GzT_biQ6YQ-CGKRVXb3aSo8ISxu9Fi1cukEgI

{
    "list": [
        {
            "typeName":"Toaster",
            "usage": 22311,
            "time": 1044
        },                
        {
            "typeName":"Iron",
            "usage": 12,
            "time": 10
        },                
        {
            "typeName":"Blender",
            "usage": 2,
            "time": 10
        }
    ]
}

###
GET http://localhost:3000/advancedCalc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b21layIsImlhdCI6MTc0ODc0MTMwNCwiZXhwIjoxNzQ4NzQzMTA0fQ.FMNu-1GzT_biQ6YQ-CGKRVXb3aSo8ISxu9Fi1cukEgI

###
POST http://localhost:3000/recomended 
Content-Type: application/json

{
    "list": [
        {
            "typeName":"Toaster",
            "usage": 2,
            "time": 10
        },                
        {
            "typeName":"Iron",
            "usage": 2,
            "time": 10
        },                
        {
            "typeName":"Blender",
            "usage": 2,
            "time": 10
        }
    ]
}
