POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"ubbbbbs1vvvv23",
    "password":"password1222"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"ubbbbbs1vvvv23",
    "password":"password1222"
}
###
POST http://localhost:3000/simpleCalc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InViYmJiYnMxdnZ2djIzIiwiaWF0IjoxNzQ4NzE2ODU3LCJleHAiOjE3NDg3MTg2NTd9.-R4nVLvbahLOo-0lycH7LCgxclurO13ltg5dgrxbVHI

{
    "usagePerMonth": 10.3,
    "pricePerKWH": 24.5,
    "fotoSize": 55.1
}
###
GET http://localhost:3000/simpleCalc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InViYmJiYnMxdnZ2djIzIiwiaWF0IjoxNzQ4NzE4NzM0LCJleHAiOjE3NDg3MjA1MzR9.VeM6HELarTpLO9mM-Yun2p9Fmcjyw4cwqViKGHgVkJc

###
GET  http://localhost:3000/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNzQ4NjkzNDc4LCJleHAiOjE3NDg3Nzk4Nzh9.k1Z2m3YgcLR-bEQzyZolwRNcNYhR60-8MERSRuHt-lw

###
POST http://localhost:3000/logout 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNzQ4NjkzNDc4LCJleHAiOjE3NDg3Nzk4Nzh9.k1Z2m3YgcLR-bEQzyZolwRNcNYhR60-8MERSRuHt-lw